server:
  port: 9900

file:
  upload:
    path: ./uploads
    allowed-extensions: txt,md

milvus:
  host: localhost
  port: 19530
  username: ""
  password: ""
  database: default
  timeout: 10000

# Spring AI Alibaba DashScope ??
spring:
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}  # ?????????????
      chat:
        options:
          timeout: 180000  # ????180??3???
      retry:
        max-attempts: 3  # ??????
        backoff:
          initial-interval: 2000  # ??????2?
          multiplier: 2  # ??????
          max-interval: 10000  # ??????10?
    # Spring AI MCP ?????
    # ????mock???????????
    mcp:
      client:
        enabled: true
        name: tencent-mcp-server
        version: 1.0.0
        request-timeout: 60s
        type: ASYNC
        sse:
          connections:
            tencent-cls:
              url: http://localhost:3000
              sse-endpoint: /sse  # ???SSE????

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



# ??? DashScope Embedding API ??
dashscope:
  api:
    key: ${DASH_SCOPE_API_KEY}  # ??????????????????????
  embedding:
    model: text-embedding-v4  # ??????????

# ??????
document:
  chunk:
    max-size: 800  # ?????????
    overlap: 100   # ??????????

# RAG ??
rag:
  top-k: 3  # ????????????
  model: "qwen3-max"  # ???????

# Prometheus ??
prometheus:
  base-url: http://localhost:9090
  timeout: 10  # ???????
  mock-enabled: true  # ???? Mock ????????

# CLS ???????
cls:
  mock-enabled: true  # ???? Mock ?????????? true ???????????????
